## Задания

**Задача 1.**

Даны четыре действительных числа: x1, y1, x2, y2. Напишите функцию distance(x1, y1, x2, y2), вычисляющая евклидово расстояние ( https://ru.wikipedia.org/wiki/%D0%95%D0%B2%D0%BA%D0%BB%D0%B8%D0%B4%D0%BE%D0%B2%D0%B0_%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D0%BA%D0%B0 ) между точкой (x1,y1) и (x2,y2).

In [1]:
import math
import numpy as np

In [4]:
def distance(x1, y1, x2, y2):
    euclid_distance = math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
    return euclid_distance

x1 = int(input("Введите координату x1: "))
y1 = int(input("Введите координату y1: "))
x2 = int(input("Введите координату x2: "))
y2 = int(input("Введите координату y2: "))

print("Евклидово расстояние: ", distance(x1, y1, x2, y2))

Евклидово расстояние:  4.242640687119285


**Задача 2.**

Написать функцию season(month), принимающую 1 аргумент — номер месяца (от 1 до 12), которая присваивает глобальной переменной s время года, которому этот месяц принадлежит (зима, весна, лето или осень).

In [2]:
def season(month):
    global s
    match month:
        case 1 | 2 | 12:
            s = "Зима"
        case 3 | 4 | 5:
            s = "Весная"
        case 6 | 7 | 8:
            s = "Лето"
        case 9 | 10 | 11:
            s = "Осень"
    return ""

month = int(input("Введите номер месяца: "))
season(month)
print("Время года: ", s)

Время года:  Лето


**Задача 3.**

Написать функцию is_prime, принимающую 1 аргумент — число от 0 до 1000, и возвращающую True, если оно простое, и False - иначе.

In [4]:
def is_prime(inputNumber):
    count = 0
    for i in range(2, int(inputNumber / 2)):
        if inputNumber % i == 0:
            count += 1
    if count > 0:
        return False
    else:
        return True

print(is_prime(2))
print(is_prime(13))
print(is_prime(14))

True
True
False


**Задача 4.**

Написать функцию reverse_list(lst), которая принимает в качестве аргумента список и возвращаем его в перевернутом виде.

Например,
- исходный список:  8, 1, 0, 4
- полученный список: 4, 0, 1, 8

Использовать встроенные функции Python нельзя. 

In [32]:
def reverse_list(lst: list):
    len_list = len(lst)
    arr = []
    for i in range(len_list - 1, -1, -1):
      arr.append(lst[i])
    return arr


lst = [1,2,3,4,5]
print(reverse_list(lst))

[5, 4, 3, 2, 1]


**Задача 5.**

Распечатайте с 4 по 8 символ фразы "Привет мир!" приведенные к верхнему регистру.

In [34]:
strHello = 'Привет мир!'

print(strHello[3:7].upper())

ВЕТ 


**Задача 6.**

Напишите код, который все элементы массива x с нечетными индексами переставит в обратном порядке.

Т.е. если x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], то код должен получать [0, 9, 2, 7, 4, 5, 6, 3, 8, 1]

In [43]:
def reverse_list(lst: list):
    lst[1::2] = reversed(lst[1::2])
    return lst


lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(reverse_list(lst))

[0, 11, 2, 9, 4, 7, 6, 5, 8, 3, 10, 1]


**Задача 7.**

Напишите цикл, который выводит все числа от 0 до 500, делящиеся на 7, если в них есть цифра 8.

In [38]:
for i in range(0, 501):
    if i % 7 == 0:
        if "8" in str(i):
            print(i)


28
84
98
168
182
189
238
280
287
308
378
385
448
483


**Задача 8.**

На вход функция more_than_five(lst) получает список из целых чисел. 
Результатом работы функции должен стать новый список, в котором содержатся только те числа, которые больше 10 по модулю.

In [37]:
def more_than_five(lst: list):
    arr = []
    for number in lst:
        if abs(number) > 10:
            arr.append(number)
    return arr

print(more_than_five([2, -15, 11, 10, 5, -100, -2]))

[-15, 11, -100]


# Задания

**Задача 1.**

Создать матрицу размером `10х10` с 0 внутри, и 1 на границах. Например для `3х3`.

```
1 1 1
1 0 1
1 1 1
```

In [50]:
array = np.ones((10, 10))
array[1:9,1:9] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Задача 2.**

Создать 5x5 матрицу с 1,2,3,4 над диагональю. Все остальные элементы - 0.

In [59]:
list = [1,2,3,4]
array = np.diag(list, k = 1)
print(array)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**Задача 3.**

Создайте случайную матрицу и вычтите из каждой строки среднее.

**Не совсем понятно, из суммы строки вычитать среднее или из каждого элемента строки? И среднее вычислять по каждой строке или по всему массиву?**
**В данном случае я вычту из суммы строки среднее по каждой строке**

In [13]:
np_array = np.random.default_rng().random((4,5))
sum_array = np_array.sum(axis = 1)
mean_array = np_array.mean(axis = 1)
result_array = sum_array - mean_array
print("Сумма по строкам: ", sum_array)
print("Среднее по строкам: ", mean_array)
print("Вычисленная матрица: ",result_array)

Сумма по строкам:  [3.23073425 2.9856422  2.0786955  2.76439433]
Среднее по строкам:  [0.64614685 0.59712844 0.4157391  0.55287887]
Вычисленная матрица:  [2.5845874  2.38851376 1.6629564  2.21151547]


**Задача 4.**

Написать функцию, принимающую на вход массив и меняющую знак у элементов, значения которых между 3 и 8. Протестировать на нескольких заданных вами массивах.

In [15]:
def change_symbol(list):
    for x in range(list.shape[0]):
        for y in range(list.shape[1]):
            if (abs(list[x,y]) > 3) and (abs(list[x, y]) < 8):
                list[x, y] *= -1
    return list
list1 = np.array([[2, -2, 1], [3, -3, 0], [9, -9, -7], [7, 6, -6]])
print("Исходная матрица: ", list1)
print("Результат работы: ", change_symbol(list1))

Исходная матрица:  [[ 2 -2  1]
 [ 3 -3  0]
 [ 9 -9 -7]
 [ 7  6 -6]]
Результат работы:  [[ 2 -2  1]
 [ 3 -3  0]
 [ 9 -9  7]
 [-7 -6  6]]


**Задача 4.**

Написать функцию, принимающую на вход массив и вычитающую среднее из каждой строки в матрице. Протестировать на нескольких заданных вами примерах.

In [29]:
def calculcate_mean(list):
    mean_number = list.mean()
    calculate_array = list - mean_number

    return calculate_array, mean_number
list1 = np.array([[2, -2, 1], [3, -3, 0], [9, -9, -7], [7, 6, -6]])
print("Исходная матрица: ", list1)
print("Среднее число матрицы: ", calculcate_mean(list1)[1])
print("Результат работы: ", calculcate_mean(list1)[0])

Исходная матрица:  [[ 2 -2  1]
 [ 3 -3  0]
 [ 9 -9 -7]
 [ 7  6 -6]]
Среднее число матрицы:  0.08333333333333333
Результат работы:  [[ 1.91666667 -2.08333333  0.91666667]
 [ 2.91666667 -3.08333333 -0.08333333]
 [ 8.91666667 -9.08333333 -7.08333333]
 [ 6.91666667  5.91666667 -6.08333333]]


**Задача 5.**

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением.

In [5]:
vector = np.array([1,2,3,4,5])
vector2 = np.zeros(17)

vector2[::4] = vector
print(vector2)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


**Задача 6.**


Написать функцию, принимающую на вход матрицу MxN и меняющую 2 любые строки в матрице. Протестировать на нескольких заданных вами примерах.

In [13]:
def change_row(array, n1, n2):
    array[[n1, n2]] = array[[n2, n1]]
    return array

example_array = np.random.default_rng().random((5,3))
print("Исходная матрица: \n", example_array)
print("Изменённая матрица: \n", change_row(example_array, 4, 3))

Исходная матрица: 
 [[0.62745419 0.43138516 0.01788892]
 [0.38646986 0.03655249 0.39078715]
 [0.8041098  0.49687562 0.78466624]
 [0.96807777 0.75283406 0.41861317]
 [0.29007804 0.6189354  0.79854111]]
Изменённая матрица: 
 [[0.62745419 0.43138516 0.01788892]
 [0.38646986 0.03655249 0.39078715]
 [0.8041098  0.49687562 0.78466624]
 [0.29007804 0.6189354  0.79854111]
 [0.96807777 0.75283406 0.41861317]]


**Задача 7.**


Написать функцию, принимающую на вход одномерный массив и возвращающую наиболее частое значение в массиве и частоту его встречи. Протестировать на нескольких заданных вами примерах.

In [17]:
def max_and_frequent(array):
    max_number = array.max()
    frequent_number = np.bincount(array).argmax()
    return max_number, frequent_number

array1 = np.array([1, 20, 20, 100])
print("Самое большое значение: ", max_and_frequent(array1)[0])
print("Самое частое значение: ", max_and_frequent(array1)[1])

Самое большое значение:  100
Самое частое значение:  20


**Задача 8.** 

Написать функцию, принимающую на вход  массив 16x16 и считающую сумму по блокам 4x4. Протестировать на нескольких заданных вами примерах.

In [24]:
def sum_4x4(array):
    for i in range(0, 16, 4):
        for k in range(0, 16, 4):
            print(np.sum(array[i:i+4, k:k+4]))

array2 = np.random.default_rng().random((16,16))
sum_4x4(array2)

6.632090407738607
7.8585545891996915
8.51412531166445
7.449338881824541
8.107764211193103
7.7526182689893055
6.894882336541258
8.560445751066647
7.35329067530876
7.8940580610303375
8.8113680516908
8.433872113039936
6.823897176279436
8.955355461797389
7.325606878259244
8.562647536736746


**Задача 9.**

Написать функцию, принимающую на вход матрицу и возвращающую n наибольших значений в массиве. n вводится с клавиатуры. Протестировать на нескольких заданных вами примерах.

In [25]:
def frequent_numbers(array, n):
    freq1 = array.reshape(-1, 1)
    freq2 = np.sort(freq1, axis=0)
    return  freq2[-n:]

array2 = np.random.default_rng().random((5,5))
n = int(input("Введите n: "))
print("Исходная матрица: \n", array2)
print(f"Наибольшие значения: \n{frequent_numbers(array2,3)}")

Исходная матрица: 
 [[0.12298204 0.36481598 0.23461335 0.05293091 0.46839137]
 [0.65423051 0.03692606 0.17878072 0.17864399 0.61142985]
 [0.24937997 0.393056   0.40871284 0.15592264 0.93117567]
 [0.26980916 0.17336244 0.8502481  0.83213781 0.82811011]
 [0.04946011 0.21593323 0.41786076 0.21558135 0.45209903]]
Наибольшие значения: 
[[0.83213781]
 [0.8502481 ]
 [0.93117567]]


**Задача 10.**

Написать функцию, принимающую на вход 10x3 матрица и находящую строки из неравных значений (например [2,2,3]). Протестировать на нескольких заданных вами примерах.

In [22]:
def not_equal(array):
    for i in range(0, 10):
        if array[i, 0] != array[i, 1] or array[i, 0] != array[i, 2] or array[i, 1] != array[i, 2]:
            print("Строка №: ", i + 1)

array2 = np.array([[2,2,3],
                   [3,3,3],
                   [4,4,4],
                   [5,5,5],
                   [6,6,6],
                   [7,7,7],
                   [8,9,9],
                   [9,9,9],
                   [10,12,1],
                   [2,1,1]])
not_equal(array2)

Строка №:  1
Строка №:  7
Строка №:  9
Строка №:  10


**Задача 11.**

Написать функцию, принимающую на вход двумерный массив и находящую все различные строки. Протестировать на нескольких заданных вами примерах.

In [31]:
def not_equal_row(array):
    for i in range(0, array.shape[0]):
        for k in range(0, array.shape[0]):
            if np.not_equal(array[i], array[k]).all():
                print(f"Строка №{i+1} не равна строке №{k+1}")

array11 = np.array([[2,2,2],
                    [3,3,3],
                    [2,2,2],
                    [3,3,3]])
not_equal_row(array11)

Строка №1 не равна строке №2
Строка №1 не равна строке №4
Строка №2 не равна строке №1
Строка №2 не равна строке №3
Строка №3 не равна строке №2
Строка №3 не равна строке №4
Строка №4 не равна строке №1
Строка №4 не равна строке №3


**Задача 12.**

Написать функцию, принимающую на вход два вектора одинакого размера и считающую расстояние между векторами. Протестировать на нескольких заданных вами примерах.

In [41]:
def vector_distance(array1, array2):
    sum_distance = 0
    for i in range(0, array1.shape[0]):
        sum_distance += ((array1[i] - array2[i]) ** 2)

    distance_num = math.sqrt(sum_distance)
    return distance_num

array1 = np.array([1,2,3,4,5])
array2 = np.array([2,3,4,5,6])

print("Расстояние: ", vector_distance(array1, array2))

Расстояние:  2.23606797749979


**Задача 13.**

Написать функцию, принимающую на вход два вектора одинакого размера и находящую косинус угла между векторами. Протестировать на нескольких заданных вами примерах.

In [109]:
def vector_cos(array1, array2):
    sum_distance = 0
    for i in range(0, array1.shape[0]):
        sum_distance += (array1[i] * array2[i])

    scalar_vectors = np.linalg.norm(array1) * np.linalg.norm(array2)
    return sum_distance / scalar_vectors

array1 = np.array([10, 4, -11])
array2 = np.array([14, 25, 4])

result_func = vector_cos(array1, array2)
print("В градусах: ", result_func)
print("В радианах: ", np.arccos(result_func))

В градусах:  0.44006737157208653
В радианах:  1.1151226278115574


**Задача 14.**

Написать функцию, принимающую на вход вектор A содержит float числа как больше, так и меньше нуля.

Функция должна округлить их до целых и результат записать в глобальную переменную Z. Округление должно быть "от нуля", т.е.:

- положительные числа округляем всегда вверх до целого
- отрицательные числа округляем всегда вниз до целого
- 0 остаётся 0

 Протестировать на нескольких заданных вами примерах.


In [202]:
def change_symbol(A):
    array1 = np.where(A > 0, A, np.floor(A))
    global Z
    Z = np.where(array1 < 0, array1, np.ceil(array1))

array = np.array([[2.0, 2.29, 2.89],
                  [-3.02, -3.8, 2.99]])
change_symbol(array)
print(Z)

[[ 2.  3.  3.]
 [-4. -4.  3.]]


**Задача 15.**

Написать функцию, принимающую на вход 2 вектора целых чисел A и B.

Функция должна находить числа, встречающиеся в обоих векторах и добавлять их по возрастанию в глобальную переменную - вектор Z.

*Если пересечений нет, то вектор Z будет пустым*.

 Протестировать на нескольких заданных вами примерах.

In [242]:
def comparison_vector(array1, array2):
    global Z
    Z = 0
    for i in range(0, array1.shape[0]):
        for k in range(0, array1.shape[0]):
            if np.equal(array1[i], array2[k]).all():
                Z = np.append(Z, array1[i])
    Z = np.delete(Z, 0)

array1 = np.array([1,2,3,4,5], int)
array2 = np.array([3,6,7,2,8,9], int)

comparison_vector(array1, array2)
print(Z)

[2 3]


**Задача 16.**

Написать функцию, принимающую на вход вектор и возвращающую максимальный элемент в векторе среди элементов, перед которыми стоит 0. 

Например для:

`x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])`

Ответ:
5

In [244]:
def max_element_of_array(array):
    zero = array == 0
    return array[1:][zero[:-1]].max()

array = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max_element_of_array(array))

5


**Задача 17.**

Написать функцию, принимающую на вход матрицу 5х3 и считающую длину каждого вектора в матрице (строка) и ищущую самый длинный вектор, вернуть его координаты и длину.

Как выглядит матрица:

```   
     | x | y | z |
     | 1 | 2 | 3 |
     | 3 | 4 | 1 |
     | ...       |
```

In [264]:
def calculate_length(array):
    sum_row = np.sum(array, axis = 1)
    max_element_value = sum_row.max()
    max_element_index = sum_row.argmax()

    return max_element_value, max_element_index

array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [1,2,3],
                  [4,5,7]])

result = calculate_length(array)
print(f"Индекс: {result[1]}\nЗначение: {result[0]}")

Индекс: 2
Значение: 24
